### PR TITLE
Automatic installation of latest versions of nuxt and laravel

### PR DESCRIPTION
**Pull request by devclouse**
Hi, please accept small updates.
- Updated containers
- Fixed in reinstall-nuxt: can't create. Because there's already a non-empty directory. Existing in path.

### CODE REVIEW

**Comment by xalaida** [comment]
Hi. Thanks a lot. Need to check it first before merging.

**Comment by xalaida** [comment]
I'm wondering if there is a way to completely delete Nuxt and Laravel folders and install them during the build process.

**Comment by devclouse** [comment]
> I'm wondering if there is a way to completely delete Nuxt and Laravel folders and install them during the build process.

Yes, I also think when make install create nuxt and laravel so that the user gets the latest version

**Comment by devclouse** [comment]
Now when you call the "make install" command, nuxt and laravel will be automatically installed, which will allow you to customize the client to fit your needs even at the installation stage

**Comment by xalaida** [comment]
@devclouse thanks again for the contribution. 
I tried install the environment from your branch but got some issues. Trying to fix them.

**Pull request merged**
